version: "3"
networks:
  usemynet:
    external:
      name: rocket_mynet
services:
  hubot:
    build:
      context: .
      dockerfile: Dockerfile-hubot
    #image: rocketchat/hubot-rocketchat:latest
    image: hubotnew_hubot:latest
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - RESPOND_TO_DM=true
      - ROCKETCHAT_ROOM=
      - LISTEN_ON_ALL_PUBLIC=true
      - ROCKETCHAT_USER=myhubot
      - ROCKETCHAT_PASSWORD=hubot123
      - BOT_NAME=bot
      - GOOGLE_API_KEY=AIzaSyCHqXtrGPeUe2RhhCLxrDhB1x6veJ4IaZw
      - HUBOT_AUTH_ADMIN=ec2-user,root
      - HUBOT_AWS_REGION=us-east-1
      - HUBOT_AWS_DEBUG=1
      - HUBOT_LOG_LEVEL=debug
      - AWS_ACCOUNT_ID=252628530222
      - AWS_S3_BILLING_BUCKET=ujwal-aws-billing
#      - NODE_DEBUG=module
  # you can add more scripts as you'd like here, they need to be installable by npm
#      - EXTERNAL_SCRIPTS=hubot-help
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
    volumes:
      - ./scripts:/home/hubot/scripts
    networks:
      - usemynet
